@startuml
!define ENTITY_UserQuestionSetHistory ' Lịch sử làm bộ câu hỏi của user
!include ../../common/IApplicationDbContext.puml

interface IUserQuestionSetHistoryService {
    ...
}
class UserQuestionSetHistoryService {
    - _context: IApplicationDbContext
    ...
}
UserQuestionSetHistoryService ..> IApplicationDbContext : <<inject>>
@enduml
