@startuml
!define ENTITY_Class ' Class
!include ../../common/IApplicationDbContext.puml
!include ../../entities/Class.puml

class CreateClassCommand {
    +Name: string
    +Topic: string
}
class CreateClassCommandHandler {
    - _context: IApplicationDbContext
    + Handle(command: CreateClassCommand, cancellationToken: CancellationToken): Task<Guid>
}
CreateClassCommandHandler ..> IApplicationDbContext : <<inject>>
@enduml 