@startuml
!define ENTITY_Class ' Class
!define ENTITY_ClassInvitation ' ClassInvitation
!include ../../common/IApplicationDbContext.puml
!include ../../entities/Class.puml
!include ../../entities/ClassInvitation.puml

actor User
participant "Class UI" as UI
participant ClassEndpoints
participant InviteStudentCommandHandler as Handler
participant ApplicationDbContext
participant Database

User -> UI : Request invite student
UI -> ClassEndpoints : POST /api/Class/{ClassId}/Invitations
ClassEndpoints -> Handler : Handle(InviteStudentCommand)

Handler -> ApplicationDbContext : Add(ClassInvitation)
ApplicationDbContext -> Database : Insert ClassInvitation
Database --> ApplicationDbContext : ClassInvitationId
ApplicationDbContext --> Handler : ClassInvitationId
Handler --> ClassEndpoints : ClassCodeDto
ClassEndpoints --> UI : 200 OK (ApiResponse<ClassCodeDto>)
UI -> User : Show invitation code
@enduml 