@startuml
!define ENTITY_Class ' Class
!define ENTITY_ClassUser ' ClassUser
!include ../../common/IApplicationDbContext.puml
!include ../../entities/Class.puml
!include ../../entities/ClassUser.puml

class JoinClassByCodeCommand {
    +ClassCode: string
    +UserId: Guid
}
class JoinClassByCodeCommandHandler {
    - _context: IApplicationDbContext
    + Handle(command: JoinClassByCodeCommand, cancellationToken: CancellationToken): Task
}
JoinClassByCodeCommandHandler ..> IApplicationDbContext : <<inject>>
@enduml 