@startuml
'=====================DEFINE========================
!define ENTITY_Class ' Class entity
!define ENTITY_ClassUser ' Class entity
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include service/IClassService.puml
!include ../../entities/Class.puml
'=====================COMMAND========================
class RemoveStudentCommand {
    +ClassId: Guid
    +UserId: Guid
}

class RemoveStudentCommandHandler {
    - _context: IApplicationDbContext
    - _classService: IClassService
    + Handle(command: RemoveStudentCommand, cancellationToken: CancellationToken): Task<Guid>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    + <<async>> RemoveStudent(classId:Guid, userId:Guid, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
RemoveStudentCommand ..|> IRequest : <<implements>>
RemoveStudentCommandHandler ..> RemoveStudentCommand :  <<uses>>
ClassEndpoints ..> RemoveStudentCommand : <<uses>>
RemoveStudentCommandHandler ..|> IRequestHandler : <<implements>>
'=====INJECT
RemoveStudentCommandHandler ..> IApplicationDbContext : <<inject>>
RemoveStudentCommandHandler ..> IClassService : <<inject>>
'=====INJECT

' Only reference entity via DbContext
@enduml 