@startuml
'=====================DEFINE========================
!define ENTITY_QuestionSet 
!define ENTITY_Question
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../entities/QuestionSet.puml
!include ../dtos/CreateUpdateQuestionDto.puml
'=====================COMMAND========================
class CreateQuestionSetCommand {
    +Name: string
    +Description: string
    +Questions : List<CreateUpdateQuestionDto>
}



class CreateQuestionSetCommandHandler {
    - _context: IApplicationDbContext
    + Handle(command: CreateQuestionSetCommand, cancellationToken: CancellationToken): Task<Guid>
}

'=====================ENDPOINT========================
class QuestionSetEndpoints  {
    + <<async>> CreateQuestionSet(command:CreateQuestionSetCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
CreateQuestionSetCommand ..|> IRequest : <<implements>>
CreateQuestionSetCommandHandler ..> CreateQuestionSetCommand :  <<uses>>
QuestionSetEndpoints ..> CreateQuestionSetCommand : <<uses>>
CreateQuestionSetCommandHandler ..|> IRequestHandler : <<implements>>
CreateQuestionSetCommand --* CreateUpdateQuestionDto 
'=====INJECT
CreateQuestionSetCommandHandler ..> IApplicationDbContext : <<inject>>
'=====INJECT

' Chỉ reference entity qua DbContext
@enduml