@startuml
title QuestionSet | DeleteQuestionSetCommand
'=====================DEFINE========================
!define QUESTIONSET_SERVICE_CANUSERDELETE
!define ENTITY_QuestionSet ' Bộ câu hỏi
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../entities/QuestionSet.puml
!include ../../common/service/IUser.puml
!include ../Services/IQuestionSetService.puml
'=====================COMMAND========================
class DeleteQuestionSetCommand {
    +Id: Guid
}
class DeleteQuestionSetCommandHandler {
    - _context: IApplicationDbContext
    + Handle(command: DeleteQuestionSetCommand, cancellationToken: CancellationToken): Task
}
'=====================ENDPOINT========================
class QuestionSetEndpoints  {
    + <<async>> DeleteQuestionSet(questionSetId:Guid, sender:ISender) : Task<Ok<ApiResponse<Unit>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
DeleteQuestionSetCommand ..|> IRequest : <<implements>>
DeleteQuestionSetCommandHandler ..> DeleteQuestionSetCommand :  <<uses>>
QuestionSetEndpoints ..> DeleteQuestionSetCommand : <<uses>>
DeleteQuestionSetCommandHandler ..|> IRequestHandler : <<implements>>
'=====INJECT
DeleteQuestionSetCommandHandler ..> IApplicationDbContext : <<inject>>
DeleteQuestionSetCommandHandler ..> IQuestionSetService : <<inject>>
DeleteQuestionSetCommandHandler ..> IUser : <<inject>>
'=====INJECT

' Chỉ reference entity qua DbContext
@enduml