@startuml
title QuestionSet |  View question set detail
'=====================DEFINE========================
!define QUESTIONSET_SERVICE_CANUSERVIEW
!define ENTITY_QuestionSet 
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IUser.puml
!include ../Services/IQuestionSetService.puml
!include ../dtos/QuestionSetDetailDto.puml
!include ../../common/IApplicationDbContext.puml
!include ../../entities/QuestionSet.puml
'=====================COMMAND========================
class GetQuestionSetDetailQuery {
    +Id: Guid
}

class GetQuestionSetDetailQueryHandler {
    - _context: IApplicationDbContext
    + Handle(query: GetQuestionSetDetailQuery, cancellationToken: CancellationToken): Task<QuestionSetDetailDto>
}
'=====================ENDPOINT========================
class QuestionSetEndpoints  {
    + <<async>> GetQuestionSetDetail(questionSetId:Guid, sender:ISender) : Task<Ok<ApiResponse<QuestionSetDetailDto>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetQuestionSetDetailQuery ..|> IRequest : <<implements>>
GetQuestionSetDetailQueryHandler ..> GetQuestionSetDetailQuery :  <<uses>>
QuestionSetEndpoints ..> GetQuestionSetDetailQuery : <<uses>>
GetQuestionSetDetailQueryHandler ..|> IRequestHandler : <<implements>>
GetQuestionSetDetailQueryHandler ..> QuestionSetDetailDto : <<uses>>
'=====INJECT
GetQuestionSetDetailQueryHandler ..> IQuestionSetService : <<inject>>
GetQuestionSetDetailQueryHandler ..> IUser : <<inject>>
'=====INJECT
' Chỉ reference entity qua DbContext
GetQuestionSetDetailQueryHandler ..> IApplicationDbContext : <<inject>>
@enduml