@startuml
title QuestionSet | UpdateQuestionSetCommand
'=====================DEFINE========================
!define QUESTIONSET_SERVICE_CANUSEREDIT
!define ENTITY_QuestionSet ' Bộ câu hỏi
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../entities/QuestionSet.puml
!include ../../common/Service/IUser.puml
!include ../Services/IQuestionSetService.puml
!include ../dtos/CreateUpdateQuestionDto.puml
'=====================COMMAND========================
class UpdateQuestionSetCommand {
    +Id: Guid
    +Name: string
    +Description: string
    +VisibilityMode: QuestionSetVisibilityMode
}
class UpdateQuestionSetCommandHandler {
    - _context: IApplicationDbContext
    + Handle(command: UpdateQuestionSetCommand, cancellationToken: CancellationToken): Task
}
'=====================RELATIONSHIP========================
!include zCommon.puml
UpdateQuestionSetCommand ..|> IRequest : <<implements>>
UpdateQuestionSetCommandHandler ..> UpdateQuestionSetCommand :  <<uses>>
QuestionSetEndpoints ..> UpdateQuestionSetCommand : <<uses>>
UpdateQuestionSetCommandHandler ..|> IRequestHandler : <<implements>>
'=====INJECT
UpdateQuestionSetCommandHandler ..> IApplicationDbContext : <<inject>>
UpdateQuestionSetCommandHandler ..> IQuestionSetService : <<inject>>
UpdateQuestionSetCommandHandler ..> IUser : <<inject>>
'=====END INJECT
UpdateQuestionSetCommand --* CreateUpdateQuestionDto 
@enduml