@startuml
class Question {
    + Id : Guid
    + QuestionSetId : Guid?
    + Type : QuestionType
    + QuestionText : string?
    + TextFormat : TextFormat
    + ExplainText : string?
    + Score : float
    + DataJson : string?
    + IsDeleted : bool
    + Data : object?
    + QuestionSet : QuestionSet
    + Comments : List<Comment>
    + UserQuestionSetHistories : List<UserQuestionSetHistory>
    + TestTemplateQuestions : List<TestTemplateQuestion>
    + TestVersionQuestions : List<TestVersionQuestion>
    + AttemptQuestions : List<AttemptQuestion>
}

@enduml 