### Change Password
POST {{baseUrl}}/api/Authentication/ChangePassword
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "currentPassword": "oldPassword123",
  "newPassword": "newPassword123"
} 