@baseUrl = http://localhost:5000
@contentType = application/json
@authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijc3Nzc3Nzc3LTc3NzctNzc3Ny03Nzc3LTc3Nzc3Nzc3Nzc3NyIsImV4cCI6MTc3MjQ1NTUzNiwiaXNzIjoiSXNzdWVyIiwiYXVkIjoiQXVkaWVuY2UifQ.MUAAwfr7bnd0w8UviYdNtnz7jBkK6rRCxcHJFo8-ZTI

############################################
### Request: POST /api/QuestionSets/Create
############################################


POST {{baseUrl}}/api/QuestionSets/Create
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
  "name": "name",
  "description": "description",
  "questions": [
    {
      "type": "type",
      "questionText": "questionText",
      "explainText": "explainText",
      "score": 0.0,
      "multipleChoices": [
        {
          "text": "text",
          "isAnswer": false
        }
      ],
      "matchingPairs": [
        {
          "leftItem": "leftItem",
          "rightItem": "rightItem"
        }
      ],
      "orderingItems": [
        {
          "text": "text",
          "correctOrder": 0
        }
      ],
      "shortAnswer": "shortAnswer"
    }
  ]
}

